module CandidateSmasherConstants
  ID_PREFIX              = "_:c"
  ABOUT_MEASURE_IRI      = "http://example.com/slowmo#IsAboutMeasure"
  ABOUT_TEMPLATE_IRI     = "http://example.com/slowmo#IsAboutTemplate"
  ANCESTOR_PERFORMER_IRI = "http://example.com/slowmo#AncestorPerformer"
  ANCESTOR_TEMPLATE_IRI  = "http://example.com/slowmo#AncestorTemplate"
  HAS_CANDIDATE_IRI      = "http://example.com/slowmo#HasCandidate"
  HAS_PERFORMER_IRI      = "http://example.com/slowmo#IsAboutPerformer"
  REGARDING_COMPARATOR   = "http://example.com/slowmo#RegardingComparator"
  REGARDING_MEASURE      = "http://example.com/slowmo#RegardingMeasure"
  SPEK_IRI               = "http://example.com/slowmo#spek"
  USES_ISR_IRI           = "http://example.com/slowmo#IsAboutCausalPathway"
  CANDIDATE_IRI          = "http://purl.obolibrary.org/obo/cpo_0000053"
  TEMPLATE_CLASS_IRI     = "http://purl.obolibrary.org/obo/psdo_0000002"
  HAS_DISPOSITION_IRI    = "http://purl.obolibrary.org/obo/RO_0000091"
  IS_ABOUT_IRI           = "http://purl.obolibrary.org/obo/IAO_0000136"
end
